env:
  browser: true
  es2021: true
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:rxjs/recommended"
  - "plugin:ngrx/recommended"
  - "plugin:@angular-eslint/eslint-plugin/recommended"
  - "plugin:security/recommended"
  - "plugin:import/recommended"
  - "plugin:import/typescript"
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 12
  project: ["tsconfig.json"]
  sourceType: module
plugins:
  - "@typescript-eslint"
  - "rxjs"
  - "ngrx"
  - "@angular-eslint/eslint-plugin"
  - "security"
  - "import"
ignorePatterns:
  - "dist/**/*"
  - "*.js"
rules:
  ngrx/avoid-dispatching-multiple-actions-sequentially: "off"
  ngrx/no-store-subscription: "off"
  security/detect-object-injection: "off"
  import/no-unresolved: "off" # false errors
  import/namespace: "off" # kills performance
  import/order: "warn"
  rxjs/no-unsafe-first: "off"
  "@typescript-eslint/no-unused-vars":
    - "warn"
    - argsIgnorePattern: "^_"
      varsIgnorePattern: "^_"
  security/detect-non-literal-fs-filename: "off"
